# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ca735e9d7f575f74e884f1832d1d1259fae10e5aeb633e16772274432e0cf13b06fd398403077237acb754082b1557389a219403574c68d73d1050fdf00d077

test:
  secret_key_base: 17bef30d268805ebd1a0f62c39be686f5e7d61c0fdf818ac8218e3f0cf84a0d75e3a87ff59603d15cea3a817a43bd82d5a9c6c8f35678ee85e8e54cc467897d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
